### ISSUE TITLE
Add new data source

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/backend#139]
### Description
Find a new data source and implement it all the way through.

Feel free to subdivide this between the two of you, or decide which one should do this and unassign the other.

### Subtasks
- [x] Find new data source (same criteria as before)
- [ ] Implement
- [ ] Test (as done with the current ones – don't test that ctor works, test that it properly parses the POCOs to graphql results by invoking the `resolver.Resolve` methods)
- [ ] Add database entry

### Additional information
- Code coverage should not decrease by the introduction of this PR

**Comment by FredrikAugust** [comment]
I think we should aim for _at least_ three data sources in the final hand-in.

It would also be cool if this data source had some parameters that the user could use.

It would be nice if this could be **finished before Sunday evening**.

**Comment by fredrikbw** [comment]
I propose using this API from SSB: https://data.ssb.no/api/v0/dataset/49613?lang=no, it contains different values from the tax settlement from 1999 to last year. This dataset is for counties, they have one for municipalities [aswell](https://data.ssb.no/api/v0/dataset/49607?lang=no), but it contains a lot of empty/duplicates of the municipalities, so we may have to filter out a lot of data. One idea could for instance be to show both the average income and the average debt over time. All the different statistical variables (income, debt, deposits etc.) could also be used as parameters for the user to use!

Would love some **yay**, **nay** or other [constructive ](https://www.youtube.com/watch?v=4n4QOIXKHZI&t=6s&ab_channel=CollinsA-Z) feedback on this 🤠

**Comment by Kpaubert** [comment]
There was a point to make a visualisation based on Trondheim/Bodø, because they have good solutions. I would personally go for your solution instead, since restricting data to two municipalities seems a bit weird given our current implementation.

Good work, Fredrik 🥇

**Comment by FredrikAugust** [comment]
Sounds good to me! 
Do you have a proposal (or several) for how this should be visualised? Especially regarding the comment about income vs. debt.

**Comment by fredrikbw** [comment]
> Sounds good to me! Great work 🏅
> Do you have a proposal (or several) for how this should be visualised? Especially regarding the comment about income vs. debt.

Yes! The idea is to introduce a barchart consisting of 2 bars per year (if income and debt were selected they would have one bar each). A line chart with two lines will also be possible. The frontend team is already working on getting this implemented!🚀
