### ISSUE TITLE
Improve mocking architecture

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/backend#16]
### Description
We should have mocking in place to reduce the required amount of outbound requests.
Take a look at how this should be implemented for the `GraphQL.Server` library.

### Subtasks
- [x] Assign project, milestone, labels and assignees
- [x] Create type (interface?) for data source so the mocked response will be identical to the actual response
- [x] Configure a mocking service
- [x] Document how to mock new queries
- [x] Take a look at "faker libraries". Libraries which help you generated dummy data in various formats. E.g. "faker" for JavaScript.

### Related information
- https://graphql-aspnet.github.io/docs/development/unit-testing 
- Blocked by #15

**Comment by FredrikAugust** [comment]
We will need to add a singleton to DI for each type;

https://graphql-dotnet.github.io/docs/getting-started/dependency-injection#aspnet-core

**Comment by FredrikAugust** [comment]
It may be smart to create an abstract data layer so the retrieval of mocked data vs real data is identical and determined by whether or not a feature flag/env variable is set.

**Comment by Kpaubert** [comment]
Started setting up a service mocking api.met's compact structure as a first step. Will probably ask for input regarding ranges of data returned, whether or not we should be strict on the data being mocked etc.

**Comment by FredrikAugust** [comment]
By the way, @Kpaubert, you can create a PR set to "WIP" if you wish to show off your progress.

**Comment by Kpaubert** [comment]
Branch updated with working mocking prototype. Seeing if I'm able to solve some of the Sider-issues.

**Comment by FredrikAugust** [comment]
Could you update the documentation, @Kpaubert? Ref. last subtask.

**Comment by Kpaubert** [comment]
Done, #38 is closed.
