### ISSUE TITLE
Create API service for MVP

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/backend#17]
### Description
We need to be able to retrieve data from an external resource. This should (probably) be handled by an API service that is injected in the service setup. 

Take a look at the current setup, and try to understand how `AddSingleton` and `AddScoped` works.

Preferably document this in the Wiki as well, as this serves as the foundation for the DI (Dependency Injection).

### Subtasks
- [x] Assign project, milestone, labels and assignees
- [x] Create API service
- [x] Add API service to DI chain (services)
- [ ] Migrate dummy data source to met.api.no

### Related sources
- https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-5.0
- Partially blocked by #16 (we should only type the response type once)
- Blocked by #15

**Comment by FredrikAugust** [comment]
Figured out how to do this, currently working on POC.

How about a quick sync tomorrow, @IT2901-SINTEF01/backend?
