### ISSUE TITLE
Document use of Docker and docker registry

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/backend#25]
### Description
As title reads. Add to README and wiki.

### Subtasks
- [x] How does the CI job to GHCR work?
- [x] How can you start Dockerfile (README)
- [x] How can you develop with the Docker image in GHCR?
