### ISSUE TITLE
Set up database and wire up to ASP.Net app

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/backend#41]
### Description
For the storage of metadata, we will need a database. Whether this is a relational or NoSQL database is up to the assignees.

Some point(s) for consideration:
- Will all metadata be equal? #40 
  - If not, will it be a hassle to create a lot of relational schemas

### Subtasks
- [x] Decide on NoSQL vs SQL
- [x] Wire up database to ASP.Net
- [x] Test (with mocks) database retrieval (if you see fit)
- [ ] Document (wiki) choice of database and setup procedures

### Related sources
- #40

**Comment by fredrikbw** [comment]
I suggest using [MongoDB](https://www.mongodb.com/). Data is stored in JSON-like documents which corresponds nicely with the use of GraphQL. It's free to use and has 512MB storage free and can scale up to 5GB.

We also discussed using Azure Cosmos, which has support for both SQL and a MongoDB API. This also appears to be a very good option. The only thing I'm concerned about is the pricing. When signing up first time you get a free trial and som credits to spend. However I'm just a little worried about this when we are still in development mode, and accidently endig up with a huge bill somehow.
If someone is familiar with Cosmos and knows how to avoid such things, then we could start using that right away. For now my suggestion is MongoDB, and then eventually migrating over to Azure Cosmos if necessarily, which seems possible: https://docs.microsoft.com/en-us/azure/dms/

**Comment by FredrikAugust** [comment]
Regarding 

> It's free to use and has 512MB storage free and can scale up to 5GB.

MongoDB is free-to-use software with no restrictions regarding size &c. Perhaps you're referring to MongoDB Atlas (what we used in "ekskom") or the MongoDB hosting on azure?

---------------------

As for the discussion on MongoDB (NoSQL) vs PostgreSQL (SQL), I agree that the combination of Mongo and GraphQL is great, and I believe it's a sensible choice. @Kpaubert, any thoughts?

**Comment by FredrikAugust** [comment]
How easy is it to connect the MongoDB server with your .NET code, @fredrikbw?
Could you perhaps set up an example that you could present to us? We could use this as a stepping stone for the final integration if we decide to rock with it.

**Comment by Kpaubert** [comment]
Using MongoDB Atlas with .NET seems (feasible and easy to implement)[https://www.mongodb.com/blog/post/quick-start-c-sharp-and-mongodb-starting-and-setup]. I think, however, the same goes for (Azure Cosmos)[https://docs.microsoft.com/en-us/azure/cosmos-db/storage-explorer], although it could require a bit more learning. Rate limiting, which is considered important in our project, can be done in the Azure Storage Explorer.

Both are valid options, and I bet this choice won't affect the system as a whole too much, but I think we should look at it together tomorrow.
@FredrikAugust @fredrikbw

**Comment by FredrikAugust** [comment]
Agree. Let's make a decision tomorrow.

**Comment by FredrikAugust** [comment]
Is this done @fredrikbw?

**Comment by fredrikbw** [comment]
Database has been documented in Wiki
