### ISSUE TITLE
Dockerise entire project with docker-compose

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/backend#43]
### Description

To make it easier to set up the project, we should use `docker-compose` to spin up the entire project.

### Subtasks
- [x] Consider reverse proxy with Nginx
- [x] Create `docker-compose.yml` file with required images
- [x] Document (wiki)
- [x] Publish in sensible place (perhaps umbrella repository)

**Comment by FredrikAugust** [comment]
Diddely-done!
See https://github.com/IT2901-SINTEF01/umbrella.
