### ISSUE TITLE
Migrate to GraphQL 4

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/backend#92]
### Description
Dependabot is nagging us with new GraphQL versions, so let's succumb to the pressure.

### Subtasks
- [x] Update all GraphQL nuget packages
- [x] Create PR
- [x] Ensure it works (and run the code:)
- [ ] Once all packages are updated, remove the stale PRs from @dependabot

### Additional resources
- [Migration guide GraphQL 3.0->4.0](https://graphql-dotnet.github.io/docs/migrations/migration4/)
