### ISSUE TITLE
Implement custom ID field on metadata fields

### ISSUE THREAD

**Issue by FredrikAugust** [IT2901-SINTEF01/backend#93]
### Description
During the implementation of proper query handling on frontend yesterday, we ran into an "issue". Issue in quotes because it's not technically a hindrance, but it shone light on an error-prone segment of our solution.

Right now, the metadata fields have no identifiable parts except for `name` and `source`[0]. To circumvent this, I propose the introduction of a custom field called `datasource_id` which has a handcrafted ID for each data source entry.

For example, the SSB population data could have the value `SSB_POPULATION`. On the backend, this should be implemented with an enum, so we can refer to the enum in GraphQL (essentially providing static typing for the field -- decreasing the likelihood of typos).

It will in turn be used in the frontend to determine what queries should be used from the metadata entry.

You can see an example of the existing solution using `title` as the "key", here:

https://github.com/IT2901-SINTEF01/frontend/pull/81/files#diff-c3f1ff461e5da26a2c4ad58527fab9c0dce7a03f5bb157f1898df18e0ab65fc4R12-R15

Furthermore, the parent-constructor call (`base(provider, "...")`) should probably use this ID, as it's a lot more legible and easier to understand. The base call would then look something along the lines of

```c#
base(provider, DataSource.MetApiForecast)
```

[0] I'm not including `id` as that is not deterministic. If you migrate the data to another database, these will be randomised, and should thus not be used for this.

### Subtasks
- [x] Create field in MongoDB and add values for both data sources
- [x] Add enum and update models in backend code
- [x] Update parent-constructor call to use new statically typed values
